# Config for multi-device LoRA finetuning in lora_finetune_distributed.py
# using a Llama3.2 11B Vision model
#
# This config assumes that you've run the following command before launching:
#   tune download meta-llama/Llama-3.2-11B-Vision --output-dir /tmp/Llama-3.2-11B-Vision --ignore-patterns "original/consolidated*"
#
# To launch on 2 devices, run the following command from root:
#   tune run --nproc_per_node 2 lora_grpo_distributed --config llama3_2_vision/11B_lora_grpo
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training:
#   tune run --nproc_per_node 2 lora_grpo_distributed --config llama3_2_vision/11B_lora_grpo checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# For single device LoRA finetuning please use 11B_lora_single_device.yaml
# or 11B_qlora_single_device.yaml

base_model_dir: ${oc.env:BASE_MODEL_DIR}
base_output_dir: ${oc.env:BASE_OUTPUT_DIR}
name: ${oc.env:CONFIG_NAME}

output_dir: ${base_output_dir}/${name}
base_model_path: ${base_model_dir}/Llama-3.2-11B-Vision  # Use this to train from the slightly trained SFT model

# Model arguments
model:
  _component_: torchtune.models.llama3_2_vision.lora_llama3_2_vision_11b
  decoder_trainable: "frozen"
  encoder_trainable: "lora"
  fusion_trainable: "lora"
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  apply_lora_to_output: False
  lora_rank: 1  # higher increases accuracy and memory
  lora_alpha: 2  # usually alpha=2*rank
  lora_dropout: 0.0
  image_size: 560 # Make sure this matches the image_size in tokenizer

# Transform
tokenizer:
  _component_: torchtune.models.llama3_2_vision.llama3_2_vision_transform
  path: ${base_model_dir}/Llama-3.2-11B-Vision/original/tokenizer.model
  image_size: 560
  max_seq_len: 8192

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${base_model_dir}/Llama-3.2-11B-Vision/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00005"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_VISION

ref_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${base_model_dir}/Llama-3.2-11B-Vision/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00005"
  recipe_checkpoint: null
  output_dir: ${output_dir}/ref
  model_type: LLAMA3_VISION


resume_from_checkpoint: False
save_adapter_weights_only: False # PeFT formatting not available yet. This will save it in torchtune format only.

# Dataset
dataset:
  _component_: torchtune.rl.gsm8k.gsm8k_dataset
  partition: 1-9/10
seed: null
shuffle: False

esume_from_checkpoint: False
save_every_n_epochs: 1

# Fine-tuning arguments
batch_size: 2
grpo_samples: 4
forward_batch_size: 1
max_generated_tokens: 512
top_k: null
temperature: 1.0

ppo_epochs: 1

num_steps: 200

clip_grad_norm: 1.0

epochs: 10
optimizer:
  _component_: torch.optim.AdamW
  lr: 1e-3
  fused: True
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 50
loss:
  _component_: torchtune.rl.loss.GRPOSimpleLoss
  kl_coeff: 0.01
  epsilon: 0.2

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True  # True reduces memory
compile: False  # pytorch compile, set to true for better perf/memory

# Reduced precision
dtype: fp32

reward_functions:
    - _component_: torchtune.rl.rewards.FormattedMathCorrectnessReward
      answer_tag: answer
      positive_reward: 10.0
      negative_reward: 0.0
    - _component_: torchtune.rl.rewards.ThinkingAnswerFormattingReward
      think_tag: think
      answer_tag: answer
      positive_reward: 1.0
      negative_reward: 0.0

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
