# Config for single device full finetuning in full_finetune_single_device.py
# using a Qwen3 4B Vision model
#
# This config assumes that you've run the following command before launching:
#   tune download Qwen/Qwen3-VL-4B-Instruct --output-dir /tmp/Qwen3-VL-4B-Instruct
#
# The default config uses an optimizer from bitsandbytes. If you do not have it installed,
# you can install it with:
#   pip install bitsandbytes
#
# To launch on a single device, run the following command from root:
#   tune run full_finetune_single_device --config recipes/configs/qwen3_vl/4b_full_single_device.yaml
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training:
#   tune run full_finetune_single_device --config qwen3_vl/4b_full_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

output_dir: /tmp/torchtune/qwen3_vl_4B/full_single_device # /tmp may be deleted by your system. Change it to your preference.

# Model arguments
model:
  _component_: torchtune.models.qwen3_vl.qwen3_vl_4b_instruct
  decoder_trainable: True
  encoder_trainable: True
  image_size: 448 # Shared with tokenizer; controls max vision pixels via Qwen processor

# Transform
tokenizer:
  _component_: torchtune.models.qwen3_vl.qwen3_vl_transform
  vocab_path: /tmp/Qwen3-VL-4B-Instruct/vocab.json
  merges_path: /tmp/Qwen3-VL-4B-Instruct/merges.txt
  special_tokens_path: /tmp/Qwen3-VL-4B-Instruct/tokenizer.json
  preprocessor_config_path: /tmp/Qwen3-VL-4B-Instruct/preprocessor_config.json
  video_preprocessor_config_path: /tmp/Qwen3-VL-4B-Instruct/video_preprocessor_config.json
  max_seq_len: 8192
  image_size: ${model.image_size}
# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen3-VL-4B-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00002"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN3_VL
resume_from_checkpoint: False

# Dataset
dataset:
  _component_: torchtune.datasets.multimodal.the_cauldron_dataset
  subset: ocrvqa
  packed: False  # True increases speed
seed: null
shuffle: True
collate_fn: torchtune.data.padded_collate_qwen_vision

# Fine-tuning arguments
epochs: 1
max_steps_per_epoch: null
batch_size: 4
gradient_accumulation_steps: 4  # Use to increase effective batch size
optimizer:
  _component_: bitsandbytes.optim.PagedAdamW8bit
  lr: 2e-5
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1

loss:
  _component_: torchtune.modules.loss.LinearCrossEntropyLoss
clip_grad_norm: 1.0
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True  # True reduces memory
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.

# Profiler (default is disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: True
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 1
  warmup_steps: 2
  active_steps: 1
  num_cycles: 1
